### ISSUE TITLE
Manifest file is also modified

### ISSUE THREAD

**Issue by GregersBoye** [unchai/webpack-manifest-replace-plugin#3]
### Reproduce:
1. Make a ```manifest.json``` file
2. Add a key-value-pair
3. Set up plugin with the following
```
    basedir: path.resolve(__dirname, 'dist'),
    src: '**/*.+(js|xml|json)',
    manifestFilename: 'manifest.json'
```

3. Run 
4. Now the value in the manifest-file has the value.
### Suggested way to resolve:
 Either ignore if file matches ```manifestFileName``` or allow an ignore-list

**Comment by unchai** [comment]
Bug has been fixed at v0.0.4. Thanks.
