### ISSUE TITLE
Build fails if building with webpack-dev-server-option

### ISSUE THREAD

**Issue by GregersBoye** [unchai/webpack-manifest-replace-plugin#4]
When building with `webpack-dev-server`-option, the build fails, because the plugin looks after the manifest file on disk only and not in-memory.

Steps to reproduce: 
1. Make sure to delete output-folder
2. Make a build using `webpack-dev-server` 
3. Get error saying that the manifest-file could not be found.

**Comment by unchai** [comment]
I'll check soon. Thanks.

**Comment by unchai** [comment]
I'm sorry for the late reply. I don't think I can support that feature in current structure. I will try to apply in the next version.
